# Build stage
FROM maven:3.6.0-jdk-11-slim AS build

#WORKDIR /src 
COPY insert_data_ny12/src /home/app/src

COPY insert_data_ny12/pom.xml /home/app

COPY insert_data_ny12/TOLLING_MODERNIZATION_TIMEZONE.jar /home/app

COPY insert_data_ny12/TimezoneUtilpom.xml /home/app

RUN mvn install:install-file -Dfile=/home/app/TOLLING_MODERNIZATION_TIMEZONE.jar -DgroupId=com.conduent.app.timezone -DartifactId=timezone_utility -Dversion=1.0.0 -DpomFile=/home/app/TimezoneUtilpom.xml


RUN mvn -f /home/app/pom.xml clean package 

# Package stage


#FROM openjdk:11-jre-slim

FROM openjdk:11-oracle

COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar

COPY insert_data_ny12/Wallet_OLTPDEV /usr/local/lib/Wallet_OLTPDEV

COPY   insert_data_ny12/oci_api_key_dev.pem /usr/local/lib/oci_api_key_dev.pem

COPY  insert_data_ny12/config_dev.txt /usr/local/lib/config_dev.txt

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar /usr/local/lib/app.jar --spring.profiles.active=dev"]
