apiVersion: apps/v1
kind: Deployment
metadata:
  name: insert-data-ny12-deployment
spec:
  selector:
    matchLabels:
      app:  insert-data-ny12
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app:  insert-data-ny12
    spec:
      containers:
      - name:  insert-data-ny12
    # enter the path to your image, be sure to include the correct region prefix    
        image: iad.ocir.io/iddewqtahvnn/tolling_qa_cont_registry:latest
        env:
        - name: DB_TPMS_USER
          valueFrom:
            secretKeyRef:
              name: db-security-tpms
              key: spring.db.tpms.username
        - name: DB_TPMS_PASSWD
          valueFrom:
            secretKeyRef:
              name: db-security-tpms
              key: spring.db.tpms.password

        volumeMounts:
        - name: nfs
          mountPath: "/QaOKEFSS/"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: ocirsecret
      dnsConfig:
        nameservers:
        - 169.254.169.254
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: oke-fsspvc1
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name:  insert-data-ny12
spec:
  #type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    #nodePort: 30016
  selector:
    app:  insert-data-ny12
