--------------------------------------------------------
--  File created - Tuesday-June-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_PLAZA_PLAN_LIMITS
--------------------------------------------------------

  CREATE TABLE "TPMS"."T_PLAZA_PLAN_LIMITS" 
   (	"ETC_ACCOUNT_ID" NUMBER(10,0), 
	"APD_ID" NUMBER(10,0), 
	"PLAZA_ENTRY" NUMBER(10,0), 
	"PLAZA_EXIT" NUMBER(10,0), 
	"UPDATE_TS" TIMESTAMP (3) WITH TIME ZONE, 
	"CSC_LOOKUP_KEY" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"CRM_ACCOUNT_ID" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTERN_ENTRY_PLAZA" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"EXTERN_EXIT_PLAZA" VARCHAR2(5 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAZA_LIMIT_ID" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
