--------------------------------------------------------
--  File created - Tuesday-June-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table V_ACCOUNT_PLAN_DETAIL
--------------------------------------------------------

  CREATE TABLE "CRM"."V_ACCOUNT_PLAN_DETAIL" 
   (	"APD_ID" NUMBER(10,0), 
	"ETC_ACCOUNT_ID" NUMBER(10,0), 
	"PLAN_TYPE" NUMBER(10,0), 
	"PLAN_STATUS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DEVICE_NO" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAN_START_DATE" DATE, 
	"PLAN_END_DATE" DATE, 
	"TRIP_COUNT" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
