--------------------------------------------------------
--  File created - Tuesday-June-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table V_DEVICE_MODEL
--------------------------------------------------------

  CREATE TABLE "CRM"."V_DEVICE_MODEL" 
   (	"MODEL_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL_DESC" VARCHAR2(255 BYTE) COLLATE "USING_NLS_COMP", 
	"UNIT_PRICE" NUMBER(22,7), 
	"DEVICE_TYPE_ID" NUMBER(10,0), 
	"DEVICE_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DEVICE_COLOR" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"MOUNT_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"AGENCY_ID" NUMBER(10,0), 
	"ROW_ID" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index V_MODEL_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CRM"."V_MODEL_NO_PK" ON "CRM"."V_DEVICE_MODEL" ("MODEL_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table V_DEVICE_MODEL
--------------------------------------------------------

  ALTER TABLE "CRM"."V_DEVICE_MODEL" ADD CONSTRAINT "V_MODEL_NO_PK" PRIMARY KEY ("MODEL_NO")
  USING INDEX "CRM"."V_MODEL_NO_PK"  ENABLE;
