--------------------------------------------------------
--  File created - Tuesday-June-15-2021   
--------------------------------------------------------

  CREATE TABLE "CRM"."V_DEVICE" 
   (	"DEVICE_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"ETC_ACCOUNT_ID" NUMBER(10,0), 
	"DEVICE_STATUS" NUMBER(10,0), 
	"DEVICE_TYPE_ID" NUMBER(10,0), 
	"IS_PREVALIDATED" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"AGENCY_CLASS" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"IAG_VEHICLE_CLASS" NUMBER(10,0), 
	"RETAIL_TAG_STATUS" NUMBER, 
	"DEVICE_DOB" DATE, 
	"STATUS_TIMESTAMP" TIMESTAMP (6), 
	"VEH_ASSOC_DATE" DATE, 
	"DATE_ASSIGNED" DATE, 
	"ISSUE_TYPE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAN_STATUS" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"DEVICE_PRICE" NUMBER(22,7), 
	"VEHICLE_ID" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"LP_CHECK_REQ" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"MODEL_ROW_ID" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"ROW_ID" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
  CREATE UNIQUE INDEX "CRM"."V_DEVICE_NO_PK" ON "CRM"."V_DEVICE" ("DEVICE_NO") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "CRM"."V_DEVICE" ADD CONSTRAINT "V_DEVICE_NO_PK" PRIMARY KEY ("DEVICE_NO")
  USING INDEX "CRM"."V_DEVICE_NO_PK"  ENABLE;

  CREATE UNIQUE INDEX "CRM"."UNIQUE_FIELD" ON "CRM"."V_DEVICE" ("DEVICE_NO", "ETC_ACCOUNT_ID") 
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
