# Build stage
FROM maven:3.6.0-jdk-11-slim AS build

#WORKDIR /src 
COPY toll_unmatchedtransx/src /home/app/src

COPY toll_unmatchedtransx/pom.xml /home/app

COPY toll_unmatchedtransx/TOLLING_MODERNIZATION_TIMEZONE.jar /home/app
COPY toll_unmatchedtransx/TimezoneUtilpom.xml /home/app
RUN mvn install:install-file -Dfile=/home/app/TOLLING_MODERNIZATION_TIMEZONE.jar -DgroupId=com.conduent.app.timezone -DartifactId=timezone_utility -Dversion=1.0.0 -DpomFile=/home/app/TimezoneUtilpom.xml

RUN mvn -f /home/app/pom.xml clean package 

# Picrxage stage
#

FROM openjdk:11-oracle

COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar

COPY toll_unmatchedtransx/Wallet_OLTPDM /usr/local/lib/Wallet_OLTPDM

COPY toll_unmatchedtransx/oci_api_key_demo.pem /usr/local/lib/oci_api_key_demo.pem

COPY toll_unmatchedtransx/config_demo.txt /usr/local/lib/config_demo.txt

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar /usr/local/lib/app.jar --spring.profiles.active=demo"]
