# Build stage
FROM maven:3.6.0-jdk-11-slim AS build

#WORKDIR /src 
COPY plan_suspension/src /home/app/src

COPY plan_suspension/pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package 

# Package stage
#

FROM openjdk:11-jre-slim

COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar

COPY plan_suspension/Wallet_OLTPDM /usr/local/lib/Wallet_OLTPDM

COPY plan_suspension/oci_api_key_demo.pem /usr/local/lib/oci_api_key_demo.pem

COPY plan_suspension/config_demo.txt /usr/local/lib/config_demo.txt

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar /usr/local/lib/app.jar --spring.profiles.active=demo"]