apiVersion: apps/v1
kind: Deployment
metadata:
  name: toll-posting-deployment
spec:
  selector:
    matchLabels:
      app:  toll-posting
  replicas: 1
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app:  toll-posting
    spec:
      containers:
      - name:  toll-posting
    # enter the path to your image, be sure to include the correct region prefix    
        image: iad.ocir.io/iddewqtahvnn/tolling_qa_cont_registry:latest
        resources:
          requests:
            cpu: "200m"
            memory: "1048Mi"
          limits:
            cpu: "200m"
            memory: "1048Mi"
        env:
        - name: DB_TPMS_USER
          valueFrom:
            secretKeyRef:
              name: db-security-tpms
              key: spring.db.tpms.username
        - name: DB_TPMS_PASSWD
          valueFrom:
            secretKeyRef:
              name: db-security-tpms
              key: spring.db.tpms.password
        - name: HOME_STREAM_ID
          valueFrom:
            configMapKeyRef:
              name: tpms-oci-streamid
              key:  config.home.streamid
        - name: IBTS_RESPONSE_QUEUE_STREAM_ID
          valueFrom:
            configMapKeyRef:
              name: tpms-oci-streamid
              key: config.ibtsQueue
        volumeMounts:
        - name: nfs
          mountPath: "/QaOKEFSS/"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: ocirsecret
      dnsConfig:
        nameservers:
        - 169.254.169.254
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: oke-fsspvc1
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name:  toll-posting-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app:  toll-posting
