CREATE TABLE "TPMS"."T_ICRX_RECON" 
   (	"PLAZA_AGENCY_ID" NUMBER(10,0), 
	"EXTER_FILE_ID" NUMBER(22,0), 
	"LANE_TX_ID" NUMBER(22,0), 
	"TX_EXTERN_REF_NO" VARCHAR2(16 BYTE) COLLATE "USING_NLS_COMP", 
	"TX_MOD_SEQ" NUMBER(10,0), 
	"ETC_TX_STATUS" NUMBER(10,0), 
	"ACCOUNT_AGENCY_ID" NUMBER(10,0), 
	"POSTED_DATE" DATE
   )