  CREATE TABLE "TPMS"."T_INTER_AGENCY_FILE_XFER" 
   (	"FILE_EXTENSION" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"FROM_DEVICE_PREFIX" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"TO_DEVICE_PREFIX" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_DATE" DATE, 
	"FILE_TIME_STRING" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"RECORD_COUNT" NUMBER(10,0), 
	"XFER_TYPE" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESS_STATUS" VARCHAR2(4 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_TS" TIMESTAMP (3) WITH TIME ZONE, 
	"FILE_NAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )
   