CREATE TABLE "TPMS"."T_OUTPUT_FIELD_MAPPING_DETAIL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"FIELD_TYPE" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FIELD_MAPPING_PK_ID" NUMBER, 
	"FIELD_NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
	"FIELD_INDEX_POSITION" NUMBER, 
	"FIELD_LENGTH" NUMBER, 
	"PAD_CHARACTER" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"JUSTIFICATION" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"FORMAT" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DEFAULT_VALUE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"CHARACTER_ENCODING" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
   )