  CREATE TABLE "TPMS"."T_OUTPUT_FIELD_MAPPING" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"AGENCY_ID" NUMBER, 
	"FILE_DESCRIPTION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_FORMAT" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"FILE_TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"PARENT_DIRECTORY" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESSED_DIRECTORY" VARCHAR2(300 BYTE) COLLATE "USING_NLS_COMP", 
	"PROCESS_TYPE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP"
   )   