  CREATE TABLE "TPMS"."T_TAGSTATUS_STATISTICS" 
   (	"FILENAME" VARCHAR2(80 BYTE) COLLATE "USING_NLS_COMP", 
	"FILEDATE" DATE, 
	"ITAG_MERGED" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DEVICE_PREFIX" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"GOOD" NUMBER(10,0), 
	"LBAL" NUMBER(10,0), 
	"ZERO" NUMBER(10,0), 
	"LOST" NUMBER(10,0), 
	"STOLEN" NUMBER(10,0), 
	"INVENTORY" NUMBER(10,0), 
	"TOTAL" NUMBER(10,0), 
	"UPDATE_TS" TIMESTAMP (3) WITH TIME ZONE, 
	"VERSION" NUMBER(12,0)
   )