# Build stage
FROM maven:3.6.0-jdk-11-slim AS build

#WORKDIR /src 
COPY ny12/src /home/app/src

COPY ny12/pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package 

# Package stage
#

FROM openjdk:11-oracle

COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar

COPY ny12/Wallet_OLTPDM /usr/local/lib/Wallet_OLTPDM

COPY ny12/oci_api_key_demo.pem /usr/local/lib/oci_api_key_demo.pem

COPY ny12/config_demo.txt /usr/local/lib/config_demo.txt

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar /usr/local/lib/app.jar --spring.profiles.active=demo"]