# Build stage
FROM maven:3.6.0-jdk-11-slim AS build

#WORKDIR /src 
COPY create_ictx/ictx_creation_scheduler/src /home/app/src

COPY create_ictx/ictx_creation_scheduler/pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package 

# Package stage


FROM openjdk:11-jre-slim

COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar

COPY create_ictx/ictx_creation_scheduler/Wallet_OLTPQA /usr/local/lib/Wallet_OLTPQA

COPY  create_ictx/ictx_creation_scheduler/oci_api_key_qa.pem /usr/local/lib/oci_api_key_qa.pem

COPY create_ictx/ictx_creation_scheduler/config_qa.txt /usr/local/lib/config_qa.txt

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar /usr/local/lib/app.jar --spring.profiles.active=qa"]
