--------------------------------------------------------
--  File created - Tuesday-June-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_TAG_STATUS_ALLSORTED
--------------------------------------------------------

  CREATE TABLE "TPMS"."T_TAG_STATUS_ALLSORTED" 
   (	"ACCOUNT_NO" VARCHAR2(16 BYTE) COLLATE "USING_NLS_COMP", 
	"ETC_ACCOUNT_ID" NUMBER(10,0), 
	"ACCOUNT_STATUS" NUMBER(3,0), 
	"ACCOUNT_TYPE" NUMBER(5,0), 
	"AGENCY_ID" NUMBER(3,0), 
	"DEVICE_NO" VARCHAR2(12 BYTE) COLLATE "USING_NLS_COMP", 
	"DEVICE_STATUS" NUMBER(10,0), 
	"FINANCIAL_STATUS" NUMBER, 
	"IAG_CODED_CLASS" NUMBER(5,0), 
	"CURRENT_BALANCE" NUMBER(10,2), 
	"REBILL_PAY_TYPE" NUMBER(10,0), 
	"REBILL_AMOUNT" NUMBER(10,2), 
	"REBILL_THRESHOLD" NUMBER(10,2), 
	"POST_PAID_STATUS" NUMBER(5,0), 
	"TAG_OWNING_AGENCY" NUMBER(5,0), 
	"THWY_ACCT" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"OPT_IN_OUT_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"ACCT_SUSP_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"POST_PAID_FLAG" CHAR(1 BYTE) COLLATE "USING_NLS_COMP", 
	"POST_PAID_PLAN_CNT" NUMBER(5,0), 
	"PREVALIDATION_FLAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"IS_COMPANION_TAG" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"FIRST_TOLL_DATE" DATE, 
	"FROM_PLAZA" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"TO_PLAZA" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"RETAIL_TAG_STATUS" NUMBER, 
	"SPEED_AGENCY" NUMBER, 
	"ITAG_TAG_STATUS" NUMBER, 
	"ITAG_INFO" NUMBER, 
	"ALL_PLANS" NUMBER, 
	"REV_PLAN_COUNT" NUMBER, 
	"NYSTA_NON_REV_COUNT" NUMBER, 
	"NYSTA_ANNUAL_PLAN_COUNT" NUMBER, 
	"NYSTA_POST_PAID_COML_COUNT" NUMBER, 
	"NYSTA_TAG_STATUS" NUMBER, 
	"NYSBA_NON_REV_COUNT" NUMBER, 
	"NYSBA_TAG_STATUS" NUMBER(10,0), 
	"MTA_NON_REV_COUNT" NUMBER, 
	"MTA_SPECIAL_PLAN_COUNT" NUMBER, 
	"MTA_TAG_STATUS" NUMBER, 
	"MTAG_PLAN_STR" NUMBER(10,0), 
	"MTA_CTRL_STR" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"PA_NON_REV_COUNT" NUMBER, 
	"PA_BRIDGES_COUNT" NUMBER, 
	"PA_SI_BRIDGES_COUNT" NUMBER, 
	"PA_CARPOOL_COUNT" NUMBER, 
	"PA_TAG_STATUS" NUMBER, 
	"RIO_NON_REV_COUNT" NUMBER, 
	"RIO_TAG_STATUS" NUMBER, 
	"RIO_CTRL_STR" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"PLZ_LIMITED_COUNT" NUMBER, 
	"FTAG_TAG_STATUS" NUMBER, 
	"FTAG_PLAN_INFO" NUMBER(10,0), 
	"TS_CTRL_STR" VARCHAR2(6 BYTE) COLLATE "USING_NLS_COMP", 
	"PLANS_STR" VARCHAR2(120 BYTE) COLLATE "USING_NLS_COMP", 
	"CSC_LOOKUP_KEY" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"UPDATE_TS" TIMESTAMP (3) WITH TIME ZONE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
