--------------------------------------------------------
--  File created - Tuesday-June-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table V_SPEED_STATUS
--------------------------------------------------------

  CREATE TABLE "CRM"."V_SPEED_STATUS" 
   (	"AGENCY_ID" NUMBER(10,0), 
	"ETC_ACCOUNT_ID" NUMBER(10,0), 
	"DEVICE_NO" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SPEED_STATUS" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"SUSPEND_DAYS" NUMBER(22,7), 
	"WARNING_MAIL_DATE" DATE, 
	"IS_FAST" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"LAST_CITATION_LEVEL" NUMBER(10,0), 
	"SPEED_STATUS_DATE" DATE, 
	"SUSPENSION_COUNT" NUMBER(22,7), 
	"APPEAL_COUNT" NUMBER(22,7), 
	"SPEED_STATUS_ID" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
