# Build stage
FROM maven:3.6.0-jdk-11-slim AS build

#WORKDIR /src 
COPY inrx_creation_scheduler/src /home/app/src

COPY inrx_creation_scheduler/pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package 

# Package stage
#

#FROM openjdk:11-jre-slim

FROM openjdk:11-oracle

COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar

COPY inrx_creation_scheduler/Wallet_OLTPUAT /usr/local/lib/Wallet_OLTPUAT

COPY  inrx_creation_scheduler/oci_api_key_dev.pem /usr/local/lib/oci_api_key_dev.pem

COPY inrx_creation_scheduler/config_dev.txt /usr/local/lib/config_dev.txt

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar /usr/local/lib/app.jar --spring.profiles.active=uat"]