# Build stage
FROM maven:3.6.0-jdk-11-slim AS build

#WORKDIR /src 
COPY create_itag/src /home/app/src

COPY create_itag/pom.xml /home/app

COPY create_itag/TOLLING_MODERNIZATION_TIMEZONE.jar /home/app

COPY create_itag/TimezoneUtilpom.xml /home/app

RUN mvn install:install-file -Dfile=/home/app/TOLLING_MODERNIZATION_TIMEZONE.jar -DgroupId=com.conduent.app.timezone -DartifactId=timezone_utility -Dversion=1.0.0 -DpomFile=/home/app/TimezoneUtilpom.xml

RUN mvn -f /home/app/pom.xml clean package 

# Package stage


FROM openjdk:11-jre-slim

COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar

COPY create_itag/Wallet_OLTPQA /usr/local/lib/Wallet_OLTPQA

COPY  create_itag/oci_api_key_qa.pem /usr/local/lib/oci_api_key_qa.pem

COPY create_itag/config_qa.txt /usr/local/lib/config_qa.txt

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar /usr/local/lib/app.jar --spring.profiles.active=qa"]
