# Build stage
FROM maven:3.6.0-jdk-11-slim AS build

#WORKDIR /src 
COPY file_parsing/pa_aet/src /home/app/src

COPY file_parsing/pa_aet/pom.xml /home/app

COPY file_parsing/pa_aet/TOLLING_MODERNIZATION_TIMEZONE.jar /home/app

COPY file_parsing/pa_aet/TimezoneUtilpom.xml /home/app

RUN mvn install:install-file -Dfile=/home/app/TOLLING_MODERNIZATION_TIMEZONE.jar -DgroupId=com.conduent.app.timezone -DartifactId=timezone_utility -Dversion=1.0.0 -DpomFile=/home/app/TimezoneUtilpom.xml

RUN mvn -f /home/app/pom.xml clean package 

# Package stage


#FROM openjdk:11-jre-slim
FROM openjdk:11-oracle

COPY --from=build /home/app/target/*.jar /usr/local/lib/app.jar

COPY file_parsing/pa_aet/Wallet_OLTPUAT /usr/local/lib/Wallet_OLTPUAT


COPY file_parsing/pa_aet/oci_api_key_dev.pem /usr/local/lib/oci_api_key_dev.pem

COPY file_parsing/pa_aet/config_dev.txt /usr/local/lib/config_dev.txt



EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar /usr/local/lib/app.jar --spring.profiles.active=uat"]
